export interface GemstoneRecommendation {
  lagna: string;
  lifeStone: { name: string; sanskritName: string; planet: string; benefit: string };
  luckyStone: { name: string; sanskritName: string; planet: string; benefit: string };
  careerStone: { name: string; sanskritName: string; planet: string; benefit: string };
  strictlyAvoid: string[];
  recommendedRudraksha: { mukhi: string; deity: string; benefit: string };
  metal: string;
  finger: string;
  pranaPratishthaDay: string;
}

export const LAGNA_GEMSTONES: Record<string, GemstoneRecommendation> = {
  "Mesha (Aries)": {
    lagna: "Mesha (Aries)",
    lifeStone: { name: "Red Coral", sanskritName: "Moonga", planet: "Mangal (Mars)", benefit: "Physical stamina, courage, vitality, and immunity." },
    luckyStone: { name: "Yellow Sapphire", sanskritName: "Pukhraj", planet: "Guru (Jupiter)", benefit: "Higher wisdom, spiritual growth, and fortune." },
    careerStone: { name: "Ruby", sanskritName: "Manikya", planet: "Surya (Sun)", benefit: "Leadership authority, confidence, and respect." },
    strictlyAvoid: ["Emerald (Panna)", "Diamond (Heera)", "Blue Sapphire (Neelam)"],
    recommendedRudraksha: { mukhi: "3 Mukhi & 5 Mukhi", deity: "Agni Dev & Lord Shiva", benefit: "Boosts confidence, purifies karmic debts, and grants peace." },
    metal: "Gold or Copper",
    finger: "Ring Finger (Anamika) of Right Hand",
    pranaPratishthaDay: "Tuesday or Thursday morning during Shukla Paksha",
  },
  "Vrishabha (Taurus)": {
    lagna: "Vrishabha (Taurus)",
    lifeStone: { name: "Diamond or White Sapphire", sanskritName: "Heera / Safed Pukhraj", planet: "Shukra (Venus)", benefit: "Grace, luxury, artistic charm, and vitality." },
    luckyStone: { name: "Blue Sapphire", sanskritName: "Neelam", planet: "Shani (Saturn)", benefit: "Massive career discipline, fortune, and structural wealth." },
    careerStone: { name: "Emerald", sanskritName: "Panna", planet: "Budha (Mercury)", benefit: "Intellect, trade, commercial sharpness, and speech." },
    strictlyAvoid: ["Ruby (Manikya)", "Red Coral (Moonga)", "Yellow Sapphire (Pukhraj)"],
    recommendedRudraksha: { mukhi: "6 Mukhi & 7 Mukhi", deity: "Kartikeya & Goddess Mahalakshmi", benefit: "Attracts financial stability, luxury, and emotional ease." },
    metal: "Silver or Platinum",
    finger: "Middle Finger (Madhyama) or Little Finger (Kanishtha)",
    pranaPratishthaDay: "Friday or Saturday morning during Shukla Paksha",
  },
  "Mithuna (Gemini)": {
    lagna: "Mithuna (Gemini)",
    lifeStone: { name: "Emerald", sanskritName: "Panna", planet: "Budha (Mercury)", benefit: "Quick intellect, mental sharpness, and business mastery." },
    luckyStone: { name: "Blue Sapphire", sanskritName: "Neelam", planet: "Shani (Saturn)", benefit: "Long-term fortune, strategic insight, and research focus." },
    careerStone: { name: "Diamond or Opal", sanskritName: "Heera / Opal", planet: "Shukra (Venus)", benefit: "Creative expression, financial abundance, and public charm." },
    strictlyAvoid: ["Red Coral (Moonga)", "Yellow Sapphire (Pukhraj)"],
    recommendedRudraksha: { mukhi: "4 Mukhi & 6 Mukhi", deity: "Lord Brahma & Lord Kartikeya", benefit: "Enhances memory, communication skills, and vocal power." },
    metal: "Gold or Silver",
    finger: "Little Finger (Kanishtha) of Right Hand",
    pranaPratishthaDay: "Wednesday morning during Shukla Paksha",
  },
  "Karka (Cancer)": {
    lagna: "Karka (Cancer)",
    lifeStone: { name: "Natural Pearl", sanskritName: "Moti", planet: "Chandra (Moon)", benefit: "Mental serenity, emotional stability, and inner peace." },
    luckyStone: { name: "Red Coral", sanskritName: "Moonga", planet: "Mangal (Mars)", benefit: "Yoga-karaka power, courage, land, and rapid prosperity." },
    careerStone: { name: "Yellow Sapphire", sanskritName: "Pukhraj", planet: "Guru (Jupiter)", benefit: "Spiritual elevation, divine luck, and wise decision-making." },
    strictlyAvoid: ["Blue Sapphire (Neelam)", "Diamond (Heera)", "Emerald (Panna)"],
    recommendedRudraksha: { mukhi: "2 Mukhi & 3 Mukhi", deity: "Ardhanarishwara & Agni Dev", benefit: "Calms emotional volatility, deepens inner peace, and purifies energy." },
    metal: "Silver or Gold",
    finger: "Little Finger (for Pearl) or Ring Finger (for Coral)",
    pranaPratishthaDay: "Monday or Tuesday morning during Shukla Paksha",
  },
  "Simha (Leo)": {
    lagna: "Simha (Leo)",
    lifeStone: { name: "Ruby", sanskritName: "Manikya", planet: "Surya (Sun)", benefit: "Soul power, natural leadership, royal prestige, and vitality." },
    luckyStone: { name: "Red Coral", sanskritName: "Moonga", planet: "Mangal (Mars)", benefit: "Bhagyodaya, courage, land ownership, and triumph over rivals." },
    careerStone: { name: "Yellow Sapphire", sanskritName: "Pukhraj", planet: "Guru (Jupiter)", benefit: "Intellect, progeny harmony, and spiritual wisdom." },
    strictlyAvoid: ["Blue Sapphire (Neelam)", "Diamond (Heera)", "Emerald (Panna)"],
    recommendedRudraksha: { mukhi: "1 Mukhi or 12 Mukhi", deity: "Surya Dev / Lord Shiva", benefit: "Infuses radiant charisma, executive authority, and clears negativity." },
    metal: "Gold or Copper",
    finger: "Ring Finger (Anamika) of Right Hand",
    pranaPratishthaDay: "Sunday morning during sunrise in Shukla Paksha",
  },
  "Kanya (Virgo)": {
    lagna: "Kanya (Virgo)",
    lifeStone: { name: "Emerald", sanskritName: "Panna", planet: "Budha (Mercury)", benefit: "Analytical prowess, financial calculation, and calm nerves." },
    luckyStone: { name: "Diamond or White Zircon", sanskritName: "Heera", planet: "Shukra (Venus)", benefit: "Prosperity, joyful family life, and material grace." },
    careerStone: { name: "Blue Sapphire", sanskritName: "Neelam", planet: "Shani (Saturn)", benefit: "Structured productivity, professional longevity, and focus." },
    strictlyAvoid: ["Red Coral (Moonga)", "Ruby (Manikya)", "Yellow Sapphire (Pukhraj)"],
    recommendedRudraksha: { mukhi: "4 Mukhi & 7 Mukhi", deity: "Lord Brahma & Goddess Mahalakshmi", benefit: "Brings immense commercial growth, sharp mind, and wealth." },
    metal: "Silver or Gold",
    finger: "Little Finger (Kanishtha) of Right Hand",
    pranaPratishthaDay: "Wednesday or Friday morning in Shukla Paksha",
  },
  "Tula (Libra)": {
    lagna: "Tula (Libra)",
    lifeStone: { name: "Diamond or Opal", sanskritName: "Heera / Opal", planet: "Shukra (Venus)", benefit: "Personal magnetism, creative mastery, and relational peace." },
    luckyStone: { name: "Blue Sapphire", sanskritName: "Neelam", planet: "Shani (Saturn)", benefit: "Yoga-karaka supreme power, fortune, and political/career triumph." },
    careerStone: { name: "Emerald", sanskritName: "Panna", planet: "Budha (Mercury)", benefit: "Spiritual balance, international trade, and insightful speech." },
    strictlyAvoid: ["Ruby (Manikya)", "Yellow Sapphire (Pukhraj)", "Red Coral (Moonga)"],
    recommendedRudraksha: { mukhi: "6 Mukhi & 7 Mukhi", deity: "Kartikeya & Mahalakshmi", benefit: "Shields against marital friction and unlocks financial expansion." },
    metal: "Platinum or Silver",
    finger: "Middle Finger (Madhyama) of Right Hand",
    pranaPratishthaDay: "Friday or Saturday morning in Shukla Paksha",
  },
  "Vrischika (Scorpio)": {
    lagna: "Vrischika (Scorpio)",
    lifeStone: { name: "Red Coral", sanskritName: "Moonga", planet: "Mangal (Mars)", benefit: "Inner drive, protection from psychic drains, and endurance." },
    luckyStone: { name: "Natural Pearl", sanskritName: "Moti", planet: "Chandra (Moon)", benefit: "Bhagyodaya, emotional intuition, and spiritual alignment." },
    careerStone: { name: "Yellow Sapphire", sanskritName: "Pukhraj", planet: "Guru (Jupiter)", benefit: "Financial abundance, family legacy, and wisdom." },
    strictlyAvoid: ["Emerald (Panna)", "Diamond (Heera)", "Blue Sapphire (Neelam)"],
    recommendedRudraksha: { mukhi: "3 Mukhi & 5 Mukhi", deity: "Agni Dev & Kalagni Rudra", benefit: "Burns past karmic stress, removes fear, and boosts self-power." },
    metal: "Gold, Copper or Brass",
    finger: "Ring Finger (Anamika) of Right Hand",
    pranaPratishthaDay: "Tuesday or Thursday morning in Shukla Paksha",
  },
  "Dhanu (Sagittarius)": {
    lagna: "Dhanu (Sagittarius)",
    lifeStone: { name: "Yellow Sapphire", sanskritName: "Pukhraj", planet: "Guru (Jupiter)", benefit: "Divine guidance, moral authority, health, and expansion." },
    luckyStone: { name: "Ruby", sanskritName: "Manikya", planet: "Surya (Sun)", benefit: "Bhagya, royal honor, fatherly blessings, and higher knowledge." },
    careerStone: { name: "Red Coral", sanskritName: "Moonga", planet: "Mangal (Mars)", benefit: "Dynamic energy, physical vitality, and triumph over hurdles." },
    strictlyAvoid: ["Emerald (Panna)", "Diamond (Heera)", "Blue Sapphire (Neelam)"],
    recommendedRudraksha: { mukhi: "5 Mukhi & 12 Mukhi", deity: "Lord Shiva & Surya Dev", benefit: "Promotes dharma, leadership power, and mental peace." },
    metal: "Pure Gold or Brass",
    finger: "Index Finger (Tarjani) or Ring Finger (Anamika)",
    pranaPratishthaDay: "Thursday or Sunday morning in Shukla Paksha",
  },
  "Makara (Capricorn)": {
    lagna: "Makara (Capricorn)",
    lifeStone: { name: "Blue Sapphire", sanskritName: "Neelam", planet: "Shani (Saturn)", benefit: "Executive discipline, immense endurance, and life direction." },
    luckyStone: { name: "Emerald", sanskritName: "Panna", planet: "Budha (Mercury)", benefit: "Bhagya, intellectual luck, trade expansion, and sharp communication." },
    careerStone: { name: "Diamond or White Sapphire", sanskritName: "Heera", planet: "Shukra (Venus)", benefit: "Yoga-karaka brilliance, career elevation, and luxury." },
    strictlyAvoid: ["Ruby (Manikya)", "Pearl (Moti)", "Red Coral (Moonga)"],
    recommendedRudraksha: { mukhi: "7 Mukhi & 14 Mukhi", deity: "Mahalakshmi & Lord Hanuman", benefit: "Bestows structural wealth, removes anxiety, and grants career mastery." },
    metal: "Silver, White Gold or Panchdhatu",
    finger: "Middle Finger (Madhyama) of Right Hand",
    pranaPratishthaDay: "Saturday or Friday morning in Shukla Paksha",
  },
  "Kumbha (Aquarius)": {
    lagna: "Kumbha (Aquarius)",
    lifeStone: { name: "Blue Sapphire", sanskritName: "Neelam", planet: "Shani (Saturn)", benefit: "Visionary clarity, steady progress, and mental resilience." },
    luckyStone: { name: "Diamond or White Opal", sanskritName: "Heera / Opal", planet: "Shukra (Venus)", benefit: "Yoga-karaka fortune, creative harmony, and domestic peace." },
    careerStone: { name: "Emerald", sanskritName: "Panna", planet: "Budha (Mercury)", benefit: "Financial gains, intellectual networking, and business sharpness." },
    strictlyAvoid: ["Ruby (Manikya)", "Pearl (Moti)", "Red Coral (Moonga)"],
    recommendedRudraksha: { mukhi: "7 Mukhi & 8 Mukhi", deity: "Goddess Mahalakshmi & Lord Ganesha", benefit: "Removes unseen obstacles, secures prosperity, and stabilizes life." },
    metal: "Silver or Panchdhatu",
    finger: "Middle Finger (Madhyama) of Right Hand",
    pranaPratishthaDay: "Saturday morning in Shukla Paksha",
  },
  "Meena (Pisces)": {
    lagna: "Meena (Pisces)",
    lifeStone: { name: "Yellow Sapphire", sanskritName: "Pukhraj", planet: "Guru (Jupiter)", benefit: "Spiritual mastery, health, wisdom, and divine protection." },
    luckyStone: { name: "Red Coral", sanskritName: "Moonga", planet: "Mangal (Mars)", benefit: "Bhagya, courage, spiritual strength, and victory." },
    careerStone: { name: "Natural Pearl", sanskritName: "Moti", planet: "Chandra (Moon)", benefit: "Emotional calm, creative intuition, and pure intellect." },
    strictlyAvoid: ["Emerald (Panna)", "Diamond (Heera)", "Blue Sapphire (Neelam)"],
    recommendedRudraksha: { mukhi: "5 Mukhi & 3 Mukhi", deity: "Lord Shiva & Agni Dev", benefit: "Calms emotional restlessness, aligns with higher dharma, and grants peace." },
    metal: "Pure Gold or Silver",
    finger: "Index Finger (Tarjani) or Ring Finger (Anamika)",
    pranaPratishthaDay: "Thursday or Monday morning in Shukla Paksha",
  },
};
