// ShubhMarg — Master Vedic Astrology Zodiac Engine
// Contains rich astrological metadata, 3D constellation nodes, and editorial reading parameters

export interface RashiInfluence {
  planet: string;
  sanskrit: string;
  effect: string;
}

export interface RashiInfo {
  id: number;
  key: string;
  en: string;
  sanskrit: string;
  hindi: string;
  glyph: string;
  rulingPlanet: string;
  rulingPlanetSymbol: string;
  element: "Agni (Fire)" | "Prithvi (Earth)" | "Vayu (Air)" | "Jala (Water)";
  elementKey: "Fire" | "Earth" | "Air" | "Water";
  elementColor: string;
  gemstone: string;
  luckyDirection: string;
  mantra: string;
  reading: string;
  guidanceText: string;
  sculpturalDescription: string;
  image?: string;
  stars: {
    love: number; // 1-5
    career: number; // 1-5
    finance: number; // 1-5
    energy: number; // 1-5
  };
  celestialInfluences: RashiInfluence[];
  constellation: [number, number, number][]; // [x, y, z] normalized points
  constellationLines: [number, number][]; // pairs of indices connecting points
}

export const RASHIS: RashiInfo[] = [
  {
    id: 0,
    key: "Mesh",
    en: "Aries",
    sanskrit: "मेष",
    hindi: "मेष",
    glyph: "♈",
    rulingPlanet: "Mangal (Mars)",
    rulingPlanetSymbol: "♂",
    element: "Agni (Fire)",
    elementKey: "Fire",
    elementColor: "#F87171",
    gemstone: "Red Coral (Moonga)",
    luckyDirection: "East (Purva)",
    mantra: "Om Kram Kreem Kroum Sah Bhaumaya Namah",
    reading: "A favourable day to act on a bold decision you have delayed. Mangal infuses high vitality, decisive authority, and courage into your ventures.",
    guidanceText: "Channel your fiery drive into structured actions rather than impulsive debates. An unexpected breakthrough awaits in leadership matters.",
    sculpturalDescription: "Realistic sculpted Ram head with majestic curling spiral gold horns, dark obsidian background, subtle crimson ember rim-lighting.",
    image: "/shubhmarg/rashi/mesh-3d.jpg",
    stars: { love: 4, career: 5, finance: 3, energy: 5 },
    celestialInfluences: [
      { planet: "Mars", sanskrit: "Mangal", effect: "High vitality & competitive drive" },
      { planet: "Sun", sanskrit: "Surya", effect: "Clarity in professional authority" },
      { planet: "Jupiter", sanskrit: "Guru", effect: "Protective trine aspect" },
    ],
    constellation: [
      [-1.4, 0.4, 0],
      [-0.4, 0.8, 0.2],
      [0.6, 0.2, -0.1],
      [1.3, -0.6, 0.1],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3]],
  },
  {
    id: 1,
    key: "Vrishabh",
    en: "Taurus",
    sanskrit: "वृषभ",
    hindi: "वृषभ",
    glyph: "♉",
    rulingPlanet: "Shukra (Venus)",
    rulingPlanetSymbol: "♀",
    element: "Prithvi (Earth)",
    elementKey: "Earth",
    elementColor: "#34D399",
    gemstone: "Diamond / White Opal",
    luckyDirection: "South (Dakshina)",
    mantra: "Om Dram Dreem Droum Sah Shukraya Namah",
    reading: "Patience brings sweet rewards today. Shukra blesses financial stability, aesthetic harmony, and domestic tranquility.",
    guidanceText: "Focus on long-term assets and creative endeavors. Ground yourself through mindful gratitude and noble hospitality.",
    sculpturalDescription: "Powerful realistic sculpted Bull head in antique bronze and gold, earthy forest-moss atmospheric depth.",
    image: "/shubhmarg/rashi/vrishabh-3d.jpg",
    stars: { love: 5, career: 4, finance: 5, energy: 4 },
    celestialInfluences: [
      { planet: "Venus", sanskrit: "Shukra", effect: "Harmonious relationship flow" },
      { planet: "Moon", sanskrit: "Chandra", effect: "Exalted emotional balance" },
      { planet: "Mercury", sanskrit: "Budha", effect: "Wise financial negotiations" },
    ],
    constellation: [
      [-1.2, 0.9, 0],
      [-0.5, 0.3, 0.1],
      [0.1, -0.1, -0.2],
      [0.8, -0.3, 0.1],
      [1.4, 0.4, 0.2],
      [0.2, 0.6, -0.1],
      [-0.8, -0.7, 0],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [3, 4], [1, 5], [2, 6]],
  },
  {
    id: 2,
    key: "Mithun",
    en: "Gemini",
    sanskrit: "मिथुन",
    hindi: "मिथुन",
    glyph: "♊",
    rulingPlanet: "Budha (Mercury)",
    rulingPlanetSymbol: "☿",
    element: "Vayu (Air)",
    elementKey: "Air",
    elementColor: "#38BDF8",
    gemstone: "Emerald (Panna)",
    luckyDirection: "North (Uttara)",
    mantra: "Om Bram Breem Broum Sah Budhaya Namah",
    reading: "Your communication is razor-sharp. Budha illuminates clarity in negotiations, intellectual writing, and trade.",
    guidanceText: "Reach out to collaborators and share your insights. A creative idea discussed today can yield fruitful alliances.",
    sculpturalDescription: "Celestial twin female maidens sculpted in high-relief gold with glowing astral halos.",
    image: "/shubhmarg/rashi/mithun-3d.jpg",
    stars: { love: 4, career: 5, finance: 4, energy: 4 },
    celestialInfluences: [
      { planet: "Mercury", sanskrit: "Budha", effect: "Sharpened cognitive speed" },
      { planet: "Venus", sanskrit: "Shukra", effect: "Graceful persuasive speech" },
      { planet: "Rahu", sanskrit: "Rahu", effect: "Unconventional solutions" },
    ],
    constellation: [
      [-0.8, 1.2, 0.1],
      [-0.7, 0.4, 0],
      [-0.5, -0.5, -0.1],
      [-0.3, -1.2, 0],
      [0.8, 1.1, -0.1],
      [0.7, 0.3, 0.1],
      [0.5, -0.6, 0],
      [0.4, -1.3, -0.1],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [4, 5], [5, 6], [6, 7], [0, 4], [1, 5], [2, 6]],
  },
  {
    id: 3,
    key: "Kark",
    en: "Cancer",
    sanskrit: "कर्क",
    hindi: "कर्क",
    glyph: "♋",
    rulingPlanet: "Chandra (Moon)",
    rulingPlanetSymbol: "☽",
    element: "Jala (Water)",
    elementKey: "Water",
    elementColor: "#818CF8",
    gemstone: "Natural Pearl (Moti)",
    luckyDirection: "North-West (Vayavya)",
    mantra: "Om Shram Shreem Shroum Sah Chandraya Namah",
    reading: "Your intuitive psychic radar is heightened today. Chandra awakens emotional depth, maternal blessings, and sanctuary peace.",
    guidanceText: "Trust your inner voice regarding family relationships and sacred spaces. Take time for meditative water rituals.",
    sculpturalDescription: "Intricate realistic oceanic Crab with burnished golden shell and deep cosmic blue water reflections.",
    image: "/shubhmarg/rashi/kark-3d.jpg",
    stars: { love: 5, career: 3, finance: 4, energy: 4 },
    celestialInfluences: [
      { planet: "Moon", sanskrit: "Chandra", effect: "Heightened psychic sensitivity" },
      { planet: "Jupiter", sanskrit: "Guru", effect: "Divine spiritual protection" },
      { planet: "Mars", sanskrit: "Mangal", effect: "Protective family instincts" },
    ],
    constellation: [
      [0, 0.7, 0.1],
      [-0.8, 0.1, -0.1],
      [0.7, -0.3, 0.2],
      [-0.3, -0.9, -0.1],
      [0.9, 0.8, 0],
    ],
    constellationLines: [[0, 1], [0, 2], [2, 3], [0, 4]],
  },
  {
    id: 4,
    key: "Simha",
    en: "Leo",
    sanskrit: "सिंह",
    hindi: "सिंह",
    glyph: "♌",
    rulingPlanet: "Surya (Sun)",
    rulingPlanetSymbol: "☉",
    element: "Agni (Fire)",
    elementKey: "Fire",
    elementColor: "#FBBF24",
    gemstone: "Ruby (Manikya)",
    luckyDirection: "East (Purva)",
    mantra: "Om Hram Hreem Hroum Sah Suryaya Namah",
    reading: "Your natural royal aura commands respect today. Surya grants effortless authority, career recognition, and divine clarity.",
    guidanceText: "Lead with magnanimity and fair judgment. A mentor or senior authority acknowledges your unwavering dedication.",
    sculpturalDescription: "Majestic sculpted royal Lion face with blazing solar ray mane and warm celestial sun halo.",
    image: "/shubhmarg/rashi/simha-3d.jpg",
    stars: { love: 4, career: 5, finance: 4, energy: 5 },
    celestialInfluences: [
      { planet: "Sun", sanskrit: "Surya", effect: "Radiant self-assurance & honor" },
      { planet: "Jupiter", sanskrit: "Guru", effect: "Dharmic expansion & wisdom" },
      { planet: "Mars", sanskrit: "Mangal", effect: "Courageous execution" },
    ],
    constellation: [
      [-1.2, -0.6, 0.1],
      [-0.8, 0.3, 0],
      [-0.3, 0.8, -0.1],
      [0.4, 0.9, 0.1],
      [0.8, 0.4, 0],
      [0.4, -0.1, -0.1],
      [1.2, -0.5, 0.2],
      [0.6, -0.9, 0],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 1], [5, 6], [6, 7]],
  },
  {
    id: 5,
    key: "Kanya",
    en: "Virgo",
    sanskrit: "कन्या",
    hindi: "कन्या",
    glyph: "♍",
    rulingPlanet: "Budha (Mercury)",
    rulingPlanetSymbol: "☿",
    element: "Prithvi (Earth)",
    elementKey: "Earth",
    elementColor: "#34D399",
    gemstone: "Emerald (Panna)",
    luckyDirection: "South (Dakshina)",
    mantra: "Om Budhaya Namaha",
    reading: "Precision and discernment will resolve a complex dilemma. Focus on wellness, nutrition, and completing detailed tasks.",
    guidanceText: "Your analytical acumen turns chaotic data into organized progress. Prioritize self-care and holistic health.",
    sculpturalDescription: "Classical sculpted celestial Maiden holding golden wheat sheaf, botanical wreath, and radiant calm.",
    image: "/shubhmarg/rashi/kanya-3d.jpg",
    stars: { love: 3, career: 5, finance: 4, energy: 4 },
    celestialInfluences: [
      { planet: "Mercury", sanskrit: "Budha", effect: "Flawless organization & logic" },
      { planet: "Saturn", sanskrit: "Shani", effect: "Methodical perseverance" },
      { planet: "Venus", sanskrit: "Shukra", effect: "Refined aesthetic eye" },
    ],
    constellation: [
      [-1.1, 0.9, 0.1],
      [-0.5, 0.4, 0],
      [0.2, 0.1, -0.1],
      [0.9, -0.2, 0.2],
      [1.3, -0.8, 0],
      [-0.2, -0.7, -0.1],
      [-0.7, -0.4, 0.1],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [3, 4], [2, 5], [5, 6], [6, 1]],
  },
  {
    id: 6,
    key: "Tula",
    en: "Libra",
    sanskrit: "तुला",
    hindi: "तुला",
    glyph: "♎",
    rulingPlanet: "Shukra (Venus)",
    rulingPlanetSymbol: "♀",
    element: "Vayu (Air)",
    elementKey: "Air",
    elementColor: "#38BDF8",
    gemstone: "White Sapphire / Diamond",
    luckyDirection: "West (Pashchima)",
    mantra: "Om Shukraya Namaha",
    reading: "Harmony returns to personal partnerships. Today's cosmic balance helps negotiate compromises where everyone wins.",
    guidanceText: "Seek beauty in balanced decisions. Legal or contractual agreements signed under this transit favor mutual equity.",
    sculpturalDescription: "Ornate golden balance scales in perfect symmetry suspended inside an astral star ring.",
    image: "/shubhmarg/rashi/tula-3d.jpg",
    stars: { love: 5, career: 4, finance: 4, energy: 4 },
    celestialInfluences: [
      { planet: "Venus", sanskrit: "Shukra", effect: "Social charm & diplomatic ease" },
      { planet: "Saturn", sanskrit: "Shani", effect: "Exalted sense of justice" },
      { planet: "Mercury", sanskrit: "Budha", effect: "Fair commercial agreements" },
    ],
    constellation: [
      [-1.0, 0.2, 0],
      [0.0, 0.8, 0.1],
      [1.0, 0.2, 0],
      [-0.6, -0.7, -0.1],
      [0.6, -0.7, 0.1],
    ],
    constellationLines: [[0, 1], [1, 2], [0, 3], [2, 4], [3, 4]],
  },
  {
    id: 7,
    key: "Vrishchik",
    en: "Scorpio",
    sanskrit: "वृश्चिक",
    hindi: "वृश्चिक",
    glyph: "♏",
    rulingPlanet: "Mangal & Ketu",
    rulingPlanetSymbol: "♂",
    element: "Jala (Water)",
    elementKey: "Water",
    elementColor: "#C084FC",
    gemstone: "Red Coral (Moonga)",
    luckyDirection: "North (Uttara)",
    mantra: "Om Kram Kreem Kroum Sah Ketave Namah",
    reading: "Deep spiritual transformation is underway. Let go of past grievances; a powerful breakthrough is about to manifest.",
    guidanceText: "Your mystical intuition penetrates all surface facades. Use your confidential strength to initiate regeneration.",
    sculpturalDescription: "Detailed realistic golden Scorpion with coiled armor and dark crimson/violet stinger energy.",
    image: "/shubhmarg/rashi/vrishchik-3d.jpg",
    stars: { love: 4, career: 4, finance: 5, energy: 5 },
    celestialInfluences: [
      { planet: "Mars", sanskrit: "Mangal", effect: "Unyielding inner resilience" },
      { planet: "Ketu", sanskrit: "Ketu", effect: "Deep esoteric comprehension" },
      { planet: "Jupiter", sanskrit: "Guru", effect: "Spiritual alchemy & protection" },
    ],
    constellation: [
      [-1.2, 0.8, 0],
      [-0.6, 0.5, 0.1],
      [0.0, 0.1, 0],
      [0.5, -0.3, -0.1],
      [0.8, -0.9, 0],
      [0.4, -1.3, 0.1],
      [-0.2, -1.1, 0],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6]],
  },
  {
    id: 8,
    key: "Dhanu",
    en: "Sagittarius",
    sanskrit: "धनु",
    hindi: "धनु",
    glyph: "♐",
    rulingPlanet: "Guru (Brihaspati)",
    rulingPlanetSymbol: "♃",
    element: "Agni (Fire)",
    elementKey: "Fire",
    elementColor: "#FACC15",
    gemstone: "Yellow Sapphire (Pukhraj)",
    luckyDirection: "North-East (Ishanya)",
    mantra: "Om Gram Greem Groum Sah Gurave Namah",
    reading: "Optimism and spiritual wisdom unlock major doors today. Seek higher knowledge, embark on a journey, or consult a mentor.",
    guidanceText: "Aim your bow at high ethical ideals. Your philosophical enthusiasm inspires others to overcome limitations.",
    sculpturalDescription: "Mythological centaur archer in sculpted gold drawing a celestial bow towards the cosmic center.",
    image: "/shubhmarg/rashi/dhanu-3d.jpg",
    stars: { love: 4, career: 5, finance: 4, energy: 5 },
    celestialInfluences: [
      { planet: "Jupiter", sanskrit: "Guru", effect: "Expansive fortune & moral clarity" },
      { planet: "Sun", sanskrit: "Surya", effect: "Academic and dharmic success" },
      { planet: "Mars", sanskrit: "Mangal", effect: "Bold adventurous zeal" },
    ],
    constellation: [
      [-1.0, -0.4, 0.1],
      [-0.3, 0.2, 0],
      [0.4, 0.8, -0.1],
      [1.1, 0.1, 0.1],
      [0.3, -0.5, 0],
      [-0.5, -0.9, -0.1],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 1], [4, 5], [5, 0]],
  },
  {
    id: 9,
    key: "Makar",
    en: "Capricorn",
    sanskrit: "मकर",
    hindi: "मकर",
    glyph: "♑",
    rulingPlanet: "Shani (Saturn)",
    rulingPlanetSymbol: "♄",
    element: "Prithvi (Earth)",
    elementKey: "Earth",
    elementColor: "#60A5FA",
    gemstone: "Blue Sapphire (Neelam)",
    luckyDirection: "West (Pashchima)",
    mantra: "Om Sham Shanaishcharaya Namah",
    reading: "Your disciplined long-term efforts begin yielding concrete results. Shani rewards patience, ethical work, and persistent focus.",
    guidanceText: "Build structural stability in professional projects. Honor elders and mentors for lasting prosperity.",
    sculpturalDescription: "Mythological horned Sea-Goat climbing obsidian cosmic peaks with weathered gold patina.",
    image: "/shubhmarg/rashi/makar-3d.jpg",
    stars: { love: 3, career: 5, finance: 5, energy: 4 },
    celestialInfluences: [
      { planet: "Saturn", sanskrit: "Shani", effect: "Disciplined endurance & karmic reward" },
      { planet: "Mercury", sanskrit: "Budha", effect: "Pragmatic enterprise strategy" },
      { planet: "Venus", sanskrit: "Shukra", effect: "Sustained long-term wealth" },
    ],
    constellation: [
      [-1.1, 0.6, 0],
      [-0.2, 0.8, 0.1],
      [0.8, 0.4, -0.1],
      [1.0, -0.3, 0.1],
      [0.2, -0.8, 0],
      [-0.7, -0.5, -0.1],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 0]],
  },
  {
    id: 10,
    key: "Kumbh",
    en: "Aquarius",
    sanskrit: "कुम्भ",
    hindi: "कुम्भ",
    glyph: "♒",
    rulingPlanet: "Shani & Rahu",
    rulingPlanetSymbol: "♄",
    element: "Vayu (Air)",
    elementKey: "Air",
    elementColor: "#38BDF8",
    gemstone: "Blue Sapphire / Hessonite",
    luckyDirection: "West (Pashchima)",
    mantra: "Om Rahave Namaha",
    reading: "An unconventional, forward-thinking idea turns out to be pure gold. Connect with visionary groups or explore technology.",
    guidanceText: "Embrace humanitarian goals and inventive methods. Your broad perspective breaks traditional bottlenecks.",
    sculpturalDescription: "Muscular celestial water bearer tilting a golden sacred kalash, pouring crystalline cosmic starlight nectar.",
    image: "/shubhmarg/rashi/kumbh-3d.jpg",
    stars: { love: 4, career: 4, finance: 5, energy: 4 },
    celestialInfluences: [
      { planet: "Saturn", sanskrit: "Shani", effect: "Social responsibility & structure" },
      { planet: "Rahu", sanskrit: "Rahu", effect: "Visionary technological breakthroughs" },
      { planet: "Venus", sanskrit: "Shukra", effect: "Harmonious community bonds" },
    ],
    constellation: [
      [-1.2, 0.4, 0.1],
      [-0.6, 0.7, 0],
      [0.1, 0.3, -0.1],
      [0.8, 0.6, 0.1],
      [1.2, 0.1, 0],
      [0.5, -0.6, -0.1],
      [-0.3, -0.8, 0],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [3, 4], [2, 5], [5, 6]],
  },
  {
    id: 11,
    key: "Meen",
    en: "Pisces",
    sanskrit: "मीन",
    hindi: "मीन",
    glyph: "♓",
    rulingPlanet: "Guru (Brihaspati)",
    rulingPlanetSymbol: "♃",
    element: "Jala (Water)",
    elementKey: "Water",
    elementColor: "#818CF8",
    gemstone: "Yellow Sapphire (Pukhraj)",
    luckyDirection: "North-East (Ishanya)",
    mantra: "Om Gurave Namaha",
    reading: "Divine grace and compassion surround you. A profound spiritual insight or sacred meditation brings deep serenity and joy.",
    guidanceText: "Surrender worries to universal divine timing. Compassionate acts performed today return multiplied blessings.",
    sculpturalDescription: "Twin golden Matsya fish swimming in yin-yang celestial orbital flow with a sacred pink lotus in center.",
    image: "/shubhmarg/rashi/meen-3d.jpg",
    stars: { love: 5, career: 4, finance: 4, energy: 4 },
    celestialInfluences: [
      { planet: "Jupiter", sanskrit: "Guru", effect: "Unconditional divine grace & intuition" },
      { planet: "Moon", sanskrit: "Chandra", effect: "Pure devotional peace" },
      { planet: "Ketu", sanskrit: "Ketu", effect: "Moksha & spiritual liberation" },
    ],
    constellation: [
      [-1.1, 0.7, 0],
      [-0.7, 0.2, 0.1],
      [-0.1, -0.4, -0.1],
      [0.6, -0.6, 0],
      [1.1, 0.1, 0.1],
      [0.9, 0.8, -0.1],
      [0.3, 0.4, 0],
    ],
    constellationLines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 2]],
  },
];
