import { getGeminiClient, GEMINI_FLASH_MODEL } from "@/lib/gemini";
import { GuidanceRequest } from "@/types/admin";
import { supabaseServer } from "@/lib/supabase";
import { fetchAdvancedPanchang } from "@/lib/astrologyapi";

export interface GeneratedReportResult {
  success: boolean;
  report?: string;
  error?: string;
}

/**
 * Generates a full Vedic astrological guidance report automatically using Gemini 3.7 Flash.
 */
export async function generateVedicGuidanceReport(
  request: GuidanceRequest
): Promise<GeneratedReportResult> {
  try {
    const ai = getGeminiClient();

    // Try fetching Panchang details if date of birth is valid
    let panchangContext = "";
    try {
      if (request.date_of_birth) {
        const [yearStr, monthStr, dayStr] = request.date_of_birth.split("-");
        const day = parseInt(dayStr, 10);
        const month = parseInt(monthStr, 10);
        const year = parseInt(yearStr, 10);
        if (!isNaN(day) && !isNaN(month) && !isNaN(year)) {
          const panchang = await fetchAdvancedPanchang(day, month, year);
          if (panchang && panchang.tithi) {
            panchangContext = `
Birth Panchang Insights:
- Tithi: ${panchang.tithi.details?.tithi_name || "N/A"}
- Nakshatra: ${panchang.nakshatra?.details?.nak_name || "N/A"}
- Yog: ${panchang.yog?.details?.yog_name || "N/A"}
- Karan: ${panchang.karan?.details?.karan_name || "N/A"}
- Paksha: ${panchang.paksha || "N/A"}
- Hindu Month: ${panchang.hindu_maah?.purnimanta || "N/A"}
`;
          }
        }
      }
    } catch {
      // Non-blocking fallback if astrology api is unreachable
    }

    const languageInstruction =
      request.preferred_language?.toLowerCase() === "hindi"
        ? "Language: Write the report in pure, respectful, authentic Hindi (Devanagari script)."
        : request.preferred_language?.toLowerCase() === "hinglish"
        ? "Language: Write the report in warm conversational Hinglish (Roman Hindi + English)."
        : `Language: Write the report in ${request.preferred_language || "English"}, keeping traditional Sanskrit/Vedic terms intact with simple explanations.`;

    const prompt = `You are Pandit Ji, a revered, wise, and deeply compassionate master of Vedic Jyotish (Vedic Astrology). You are preparing a comprehensive, sacred, and personalized astrological guidance report for a seeker.

SEEKER DETAILS:
- Full Name: ${request.full_name}
- Date of Birth: ${request.date_of_birth}
- Time of Birth: ${request.time_of_birth || "Unknown / Approximate"}
- Place of Birth: ${request.birth_place}
- Current City: ${request.current_city}
- Requested Service: ${request.service.toUpperCase()}
- Area of Concern: ${request.concern}
- Seeker's Specific Question / Situation:
"""${request.question}"""

${panchangContext}

${languageInstruction}

REPORT STRUCTURE & REQUIREMENTS:
1. **Divine Invocation & Blessing (Mangalacharan):** Start with an auspicious Vedic shloka and a warm blessing for ${request.full_name}.
2. **Chart & Energy Analysis:**
   - Analyse the astrological planetary influences related to their concern.
   - Explain how current transits (Gochara) and planetary periods (Dasha) influence their situation.
3. **Direct Answer to Seeker's Question:**
   - Give clear, honest, and grounded guidance regarding their specific question.
   - Outline the key timeline / favorable windows in the coming months.
4. **Practical Vedic Remedies (Upayas):**
   - Provide 3-4 simple, sattvic remedies (e.g., specific mantra chanting, charity/daan on specific days, dietary or lifestyle alignment).
   - Ensure remedies are practical, positive, and free of fear.
5. **Closing Words of Strength & Blessing:**
   - Encourage faith, karma, and right action (Purushartha).

TONE:
- Reassuring, authoritative, ethical, and compassionate.
- Avoid fear-mongering (do not make fatalistic predictions).
- Do not promise guaranteed lottery/medical cures; emphasize spiritual and practical alignment.`;

    const response = await ai.models.generateContent({
      model: GEMINI_FLASH_MODEL,
      contents: prompt,
      config: {
        temperature: 0.7,
        maxOutputTokens: 2500,
      },
    });

    const reportText = response.text || "";

    if (!reportText) {
      return { success: false, error: "Empty response generated by AI model." };
    }

    // Save generated report to database and update status
    await supabaseServer
      .from("guidance_requests")
      .update({
        notes: reportText,
        status: "completed",
      })
      .eq("id", request.id);

    return { success: true, report: reportText };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("Automated report generation error:", errorMsg);
    return { success: false, error: errorMsg };
  }
}
